version: '3.8'
services:
  db:
    image: postgres
    container_name: RentCar
    restart: always
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres